import {supabase,shell,setApp,esc,toast,openModal,canManage,qs,money,fmtDate,csvDownload,logActivity} from "./app.js";
const p=await shell("Finance");if(!p)throw 0;
async function load(){
 const [{data:funds,error:fe},{data:tx,error:te}]=await Promise.all([supabase.from("cash_funds").select("*").order("name"),supabase.from("finance_transactions").select("*,cash_funds(name)").order("transaction_date",{ascending:false}).order("created_at",{ascending:false})]);if(fe||te)throw fe||te;
 setApp(`<div class="flex justify-between items-end mb-5"><div><h1 class="text-3xl font-black">Finance</h1><p class="text-slate-500">Track funds and financial transactions.</p></div><div class="flex gap-2"><button id="export" class="btn btn-secondary">Export CSV</button>${canManage(p,"manage_finance")?`<button id="add" class="btn btn-primary">+ Transaction</button>`:""}</div></div><div class="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">${(funds||[]).map(f=>`<div class="stat"><div class="font-bold">${esc(f.name)}</div><div class="text-2xl font-black mt-2">${money(f.balance)}</div><div class="text-xs text-slate-500">${esc(f.status)}</div></div>`).join("")}</div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Fund</th><th>Amount</th></tr></thead><tbody>${(tx||[]).map(x=>`<tr><td>${fmtDate(x.transaction_date)}</td><td><span class="badge ${x.type==="income"?"badge-green":"badge-red"}">${esc(x.type)}</span></td><td>${esc(x.description)}</td><td>${esc(x.cash_funds?.name||"—")}</td><td class="font-bold">${money(x.amount)}</td></tr>`).join("")||`<tr><td colspan="5" class="text-center py-8 text-slate-500">No transactions.</td></tr>`}</tbody></table></div>`);
 if(canManage(p,"manage_finance"))qs("#add").onclick=()=>form(funds||[]);
 qs("#export").onclick=()=>csvDownload((tx||[]).map(x=>({date:x.transaction_date,type:x.type,description:x.description,fund:x.cash_funds?.name||"",amount:x.amount})),"osi-finance.csv");
}
function form(funds){const m=openModal("Add transaction",`<form id="f" class="grid sm:grid-cols-2 gap-4"><div><label class="label">Type</label><select class="select" name="type"><option>income</option><option>expense</option></select></div><div><label class="label">Amount *</label><input class="input" name="amount" type="number" min=".01" step=".01" required></div><div><label class="label">Fund *</label><select class="select" name="fund_id" required>${funds.filter(f=>f.status==="active").map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join("")}</select></div><div><label class="label">Date</label><input class="input" name="transaction_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="sm:col-span-2"><label class="label">Description *</label><input class="input" name="description" required></div><button class="btn btn-primary sm:col-span-2">Save transaction</button></form>`);qs("#f",m).onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.amount=Number(d.amount);d.created_by=p.id;const r=await supabase.from("finance_transactions").insert(d);if(r.error){toast(r.error.message,false);return}await logActivity("Created finance transaction","finance_transactions",null,{type:d.type,amount:d.amount});toast("Transaction saved");m.remove();load()}}
load().catch(e=>toast(e.message,false));
