import {supabase,shell,setApp,esc,toast,openModal,canManage,qs,fmtDate,logActivity} from "./app.js";
const p=await shell("Requests");if(!p)throw 0;
async function load(){
 const {data,error}=await supabase.from("borrow_requests").select("*,inventory_items(name,item_code),profiles:requested_by(full_name,email)").order("created_at",{ascending:false});if(error)throw error;
 setApp(`<div class="flex justify-between items-end mb-5"><div><h1 class="text-3xl font-black">Borrow Requests</h1><p class="text-slate-500">Submit and review requests for inventory.</p></div></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Item</th><th>Requester</th><th>Qty</th><th>Borrow date</th><th>Due</th><th>Purpose</th><th>Status</th><th>Actions</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td class="font-bold">${esc(x.inventory_items?.name||"—")}<div class="text-xs text-slate-500">${esc(x.inventory_items?.item_code||"")}</div></td><td>${esc(x.profiles?.full_name||"—")}</td><td>${x.quantity}</td><td>${fmtDate(x.borrow_date)}</td><td>${fmtDate(x.return_due)}</td><td>${esc(x.purpose||"—")}</td><td><span class="badge ${x.status==="approved"?"badge-green":x.status==="pending"?"badge-orange":x.status==="rejected"?"badge-red":"badge-gray"}">${esc(x.status)}</span></td><td>${canManage(p,"manage_requests")&&x.status==="pending"?`<div class="flex gap-2"><button class="approve btn btn-primary !py-1.5" data-id="${x.id}">Approve</button><button class="reject btn btn-danger !py-1.5" data-id="${x.id}">Reject</button></div>`:"—"}</td></tr>`).join("")||`<tr><td colspan="8" class="text-center py-8 text-slate-500">No requests found.</td></tr>`}</tbody></table></div>`);
 document.querySelectorAll(".approve").forEach(b=>b.onclick=()=>review(b.dataset.id,"approved"));document.querySelectorAll(".reject").forEach(b=>b.onclick=()=>review(b.dataset.id,"rejected"));
}
async function review(id,status){if(!confirm(`${status==="approved"?"Approve":"Reject"} this request?`))return;let r;if(status==="approved")r=await supabase.rpc("approve_borrow_request",{p_request_id:id});else r=await supabase.from("borrow_requests").update({status,reviewed_by:p.id,reviewed_at:new Date().toISOString()}).eq("id",id);if(r.error){toast(r.error.message,false);return}await logActivity(`${status==="approved"?"Approved":"Rejected"} borrow request`,"borrow_requests",id,{});toast(`Request ${status}`);load()}
load().catch(e=>toast(e.message,false));
