import {supabase,shell,setApp,esc,toast,openModal,canManage,qs,fmtDate,logActivity} from "./app.js";
const p=await shell("Returns");if(!p)throw 0;
if(!canManage(p)){setApp(`<div class="card p-8"><h1 class="text-2xl font-black">Admin access required</h1><p class="text-slate-500 mt-2">Returns are processed by inventory administrators.</p></div>`);throw 0}
async function load(){
 const {data,error}=await supabase.from("borrowings").select("*,inventory_items(name,item_code),profiles:borrower_id(full_name)").in("status",["active","overdue"]).order("return_due");if(error)throw error;
 setApp(`<div class="mb-5"><h1 class="text-3xl font-black">Returns</h1><p class="text-slate-500">Process returned property and update inventory.</p></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Item</th><th>Borrower</th><th>Qty</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td class="font-bold">${esc(x.inventory_items?.name||"—")}</td><td>${esc(x.profiles?.full_name||"—")}</td><td>${x.quantity}</td><td>${fmtDate(x.return_due)}</td><td><span class="badge badge-orange">${esc(x.status)}</span></td><td><button class="return btn btn-primary !py-1.5" data-id="${x.id}">Process return</button></td></tr>`).join("")||`<tr><td colspan="6" class="text-center py-8 text-slate-500">No active borrowings.</td></tr>`}</tbody></table></div>`);
 document.querySelectorAll(".return").forEach(b=>b.onclick=()=>form(b.dataset.id));
}
function form(id){const m=openModal("Process return",`<form id="f" class="space-y-4"><div><label class="label">Condition on return</label><select name="condition" class="select"><option>good</option><option>fair</option><option>damaged</option><option>lost</option></select></div><div><label class="label">Notes</label><textarea name="notes" class="textarea"></textarea></div><button class="btn btn-primary w-full">Complete return</button></form>`);qs("#f",m).onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const r=await supabase.rpc("return_borrowing",{p_borrowing_id:id,p_condition:d.condition,p_notes:d.notes||null,p_returned_by:p.id});if(r.error){toast(r.error.message,false);return}await logActivity("Processed return","borrowings",id,{condition:d.condition});toast("Return completed");m.remove();load()}}
load().catch(e=>toast(e.message,false));
